# Учебные данные: цены и конфигурации будут уточнены позже.
PRODUCTS = [{'id': 1,
  'name': 'Iron Pulse',
  'category': 'game',
  'condition': 'new',
  'price': 429000,
  'cpu': 'Ryzen 5 5600',
  'gpu': 'GeForce RTX 4060',
  'ram': '16 ГБ DDR4',
  'disk': '1 ТБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-1.svg',
  'description': 'Для игр, общения и повседневных задач.'},
 {'id': 2,
  'name': 'Iron Vector',
  'category': 'office',
  'condition': 'new',
  'price': 189000,
  'cpu': 'Core i3-12100',
  'gpu': 'Intel UHD 730',
  'ram': '16 ГБ DDR4',
  'disk': '512 ГБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-2.svg',
  'description': 'Для документов, браузера и учёбы.'},
 {'id': 3,
  'name': 'Iron Forge',
  'category': 'work',
  'condition': 'new',
  'price': 899000,
  'cpu': 'Ryzen 9 7900',
  'gpu': 'GeForce RTX 4070 SUPER',
  'ram': '64 ГБ DDR5',
  'disk': '2 ТБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-3.svg',
  'description': 'Для ресурсоёмких рабочих задач.'},
 {'id': 4,
  'name': 'Iron Shift',
  'category': 'game',
  'condition': 'used',
  'price': 249000,
  'cpu': 'Ryzen 5 3600',
  'gpu': 'GeForce RTX 2060',
  'ram': '16 ГБ DDR4',
  'disk': '512 ГБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-1.svg',
  'description': 'Для игр, общения и повседневных задач.'},
 {'id': 5,
  'name': 'Iron Apex',
  'category': 'game',
  'condition': 'new',
  'price': 699000,
  'cpu': 'Ryzen 7 7700',
  'gpu': 'GeForce RTX 4070',
  'ram': '32 ГБ DDR5',
  'disk': '1 ТБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-2.svg',
  'description': 'Для игр, общения и повседневных задач.'},
 {'id': 6,
  'name': 'Iron Desk',
  'category': 'office',
  'condition': 'used',
  'price': 99000,
  'cpu': 'Core i5-8400',
  'gpu': 'Intel UHD 630',
  'ram': '8 ГБ DDR4',
  'disk': '256 ГБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-3.svg',
  'description': 'Для документов, браузера и учёбы.'},
 {'id': 7,
  'name': 'Iron Studio',
  'category': 'work',
  'condition': 'new',
  'price': 549000,
  'cpu': 'Core i5-13400F',
  'gpu': 'GeForce RTX 4060 Ti',
  'ram': '32 ГБ DDR4',
  'disk': '1 ТБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-1.svg',
  'description': 'Для ресурсоёмких рабочих задач.'},
 {'id': 8,
  'name': 'Iron Base',
  'category': 'office',
  'condition': 'new',
  'price': 239000,
  'cpu': 'Ryzen 5 5600G',
  'gpu': 'Radeon Graphics',
  'ram': '16 ГБ DDR4',
  'disk': '1 ТБ SSD',
  'board': 'Совместимая плата AM4 / AM5 / LGA — уточняется',
  'psu': 'Блок питания под конфигурацию — уточняется',
  'os': 'Ubuntu LTS',
  'image': '/static/images/products/pc-2.svg',
  'description': 'Для документов, браузера и учёбы.'}]
